### PR TITLE
Avoid calling response.json() with no response.content

### PR DESCRIPTION
**Pull request by leadZERO**
Avoids throwing an awkward json() exception when looking for notifications.

### CODE REVIEW

**Comment by blacktop** [comment]
Thank you for catching this @leadZERO 

I don't have access to the Intel API anymore so I can't test those APIs anymore 😢 , however, in other API endpoints I would check for:

```python
        if response.ok:
            return response.content
```

before outputting to JSON etc.

Can you tell me if that would also fix it?  If so I would like to standardize on that way of handling empty content?

**Comment by leadZERO** [comment]
Just doing "response.ok" could not fix the issue directly. The VT API will return response.ok and empty content if the provided API key is good but there are no notifications. The code before the change:
`try:
    response = requests.get(self.base + 'hunting/notifications-feed/', params=params, proxies=self.proxies, timeout=timeout)
    return response.json().get('next'), response
except requests.RequestException as e:
    return dict(error=str(e))`
The problem is response.json() will throw is response.content is empty. 

The current API with this module returns two values, the Next page id to be passed back to the VT api and the response object. One possible solution would be to just return the response object and let someone consuming the module deal with it. This could be considered a significant change though and would likely require a change to any consumer of the intel notifications api. 

A lighter change, slightly different than mine, would be to move the `return None, response` to an except block to catch the JSON error.

**Comment by MrRedAmber** [comment]
I tried looking all over for the VT intel documentation, I don't think we can implement this and be totally secure that it works unless we have someone with VT intel test it or give us the docs 🐳

**Comment by leadZERO** [comment]
I have access to VT Intel. That's how I discovered the fact that that the json feed from VTI returned response.OK for a valid request when there were no notifications pending and thus returned no content.

I tested my original PR, but would be happy to test any and proposed solution.

**Comment by blacktop** [comment]
It's seems to me that this is a problem with how VT designed their Intel API, but I think from a user of this python package, they would expect to still get JSON back, but with an error in it like the one they would get with a `requests.RequestException`, but it being empty isn't an error it just doesn't have any new `feed` items.  

Do you know what the JSON looks like if it does have responses @leadZERO ?  If so I think it would be correct for example if the response has a JSON field that is an array of notifications that we would craft a JSON response like how VT should have that just contains an empty array?

Does that make sense?

**Comment by leadZERO** [comment]
Sure,

This is vaguely what a response looks like when notifications are present:
```json
{
    "notifications": [ ... ],
    "verbose_msg": "Rules produced matches, notifications embedded in this object",
    "result": 1,
    "next": null
}
```
If more than 1 response is required for all pending notifications, the "next" parameter will contain a reference to be passed to a subsequent call. 

So, just to make sure I understand you correctly... Your opinion would be to emulate the above but with an empty "notifications" array? I think that makes sense and is a bit more elegant. However, it will depart from the current functionality. Currently a tuple of the "next" parameter and response object is returned. I tend to agree that passing back the entire response object probably isn't the best way. Other aspects of the PublicApi and PrivateApi pass JSON back utilize the _return_response_and_status_code function to handle the response. We could handle this similarly.

**Comment by blacktop** [comment]
That sounds perfect!

**Comment by blacktop** [comment]
So something like:

```json
{
    "notifications": [],
    "verbose_msg": "Rules produced no matches",
    "result": 0,
    "next": null,
    "status_code":  resp.status_code
} 
```

**Comment by leadZERO** [comment]
Updated. I also have changes prepared to cleanup a lot of the returns to match the PublicApi and PrivateApi. Most functions use _return_response_and_status_code(). A number of functions duplicate this function for local differences. I have a few suggestions to clean those up and avoid duplicating code. But I'll submit that as another PR once we get a format for this one that looks good.

With this one, I like having get_intel_notifications use the same _return_response_and_status_code() function for get_intel_notifications. I didn't like using a fake object (since the content property of Response objects isn't writeable). But, if and when VT updates the Intel API, that can be removed and then the function will be just like all the others. And would not require an update on any downstream code. That I like...

**Comment by blacktop** [comment]
Sorry for the delay in my response. 🎅 🎄 

I believe it might be eaiser to just update the dict values for those fields instead of creating that helper class?

**Comment by leadZERO** [comment]
Good idea! I hadn't considered reaching beyond the content property to update it. How's that look?

**Comment by blacktop** [comment]
hmmm yeah I see why you did both solutions the way you did, to try and adhere to the pattern of using the helper method: `_return_response_and_status_code`

I don't know that any solution will "feel" good as we are fixing a problem that is on VT's side.

**Comment by blacktop** [comment]
I think you have come up with a very succinct solution, but do you think it is better than pulling the contents of the helper method into that offending function that way you don't have to patch the binary data?

I honestly don't know, both ways feel kinda gross.

**Comment by leadZERO** [comment]
I'm ok with it. Mainly because it's correcting for what I consider an error in the API. And I submitted it to VT and the person that responded seemed to think so as well. Now, who knows when (if?) it will be fixed. But, that only means those 2 lines have to be removed at that point. I think it's the cleanest option.

**Comment by blacktop** [comment]
Right on, let's put this PR to rest.

Thank you for this 👍 and thank you for helping FOSS 👏

**Pull request merged**
