### PR TITLE
Allow passing scan_file a file object from memory.

### LINKED ISSUE #8: Allow passing scan_file a file object from memory.
I would like to be able to submit files that i don't have on disk. Instead of passing the filepath to the scan_file function I would like to give it a reference to the file object in memory.

### PR DESCRIPTION
**Pull request by tweemeterjop**
Added an extra parameter to the the scan_file function that indicates if the this_file parameter should be interpreted as a filepath or file object. If True we read from disk, else we pass the object straight to the API. This goes for both the Public and Private API.

This fixes #8.

### CODE REVIEW

**Comment by tweemeterjop** [comment]
You might want to add a new test case for this scenario.

**Comment by blacktop** [comment]
Can you change `read_file` to `on_disk` or `from_disk` I think that flag is more self explanatory to users as to what it is for.

**Comment by blacktop** [comment]
This is a great pull request much thanks!!!  I used to support streams, but removed it for some reason when I decided to support python 2 and 3.  Thank you for bringing it back :)

**Comment by tweemeterjop** [comment]
Thanks for merging this and creating a PyPi package. Cheers!

**Pull request merged**
