### PR TITLE
timeout functionality

### PR DESCRIPTION
**Pull request by MrRedAmber**
🐳

### CODE REVIEW

**Comment by blacktop** [comment]
ummmm - https://github.com/blacktop/virustotal-api#contributing

Can you please update the HISTORY.rst as well kind sir?

**Comment by MrRedAmber** [comment]
@blacktop updated

**Comment by blacktop** [comment]
LGTM

**Comment by blacktop** [comment]
Closes #11

**Comment by blacktop** [comment]
good job... but... do you EVEN dock bro!?!? 🐋 🐳

**Pull request merged**
